### ISSUE TITLE
Web ERROR while uploading loom/h5ad: 'dict' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by levinhein** [gao-lab/Cell_BLAST#11]
Hello. I tried to upload my `.loom` file and `.h5ad` file of gene expression matrix at the Cell BLAST website, but it returned an error.

```
An error occurred while processing the h5ad file.
'dict' object has no attribute 'dtype'
```
May I ask what is the likely reason for this and what should I do? Thanks!

**Comment by Jeff1995** [comment]
Thanks for the report! I just tried several h5ad files on my own and they seem to work fine. Could you please provide a test h5ad file that produces the error (via a dropbox link etc.), so I may track down the problem?

**Comment by levinhein** [comment]
Sure, can you please check my files? 

`https://drive.google.com/drive/folders/1jiKcDgAdOYDFfolOZWDCBXiQ9sQuh_vv?usp=sharing`

**Comment by Jeff1995** [comment]
Thanks! Just verified that the error was raised from within the `anndata.read_h5ad` function. It seems to be caused by incompatible anndata versions, as it only happens in v0.6.22 (version used on our web server), and everything works fine after upgrading to the latest v0.7.4.

Though this problem has been fixed, one additional problem is that the provided dataset exceeds the maximal cell number of 20,000 on our Web server. You may need to split it into several smaller chunks.

Let me know if any further issues.
