### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [gao-lab/Cell_BLAST#17]
Hi,
Thanks for developing such a good tool. I want to try to use it, but I can not open the website https://cblast.gao-lab.org/download . And I can not find the Tutorial on how to use this tool. Please help me.
Thanks.

**Comment by Jeff1995** [comment]
Thanks for the report! The website is now back online.

**Comment by ZHIDIHUAYUAN** [comment]
Thanks for your apply.
When I use the websit to analyze my data, The page always shows parsing file content. It's been like this for more than ten hours. Is this normal? When I click the download, it shows nginx error!
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/66869156/111100081-e689d480-8581-11eb-8e4f-104b1dfd2af7.png">

What should I do?

**Comment by Jeff1995** [comment]
Sorry for the inconvenience. We fixed the main page but the download page still would not load. Now it has been fixed.

Btw, the documentation can be found [here](https://cblast.gao-lab.org/doc-latest/index.html).

**Comment by ZHIDIHUAYUAN** [comment]
Thanks very much!
I got the result.
![image](https://user-images.githubusercontent.com/66869156/111119236-d9caa800-85a4-11eb-9275-9a853ec7f7dc.png)
Is it true that only the annotations with p-values less than 0.05 are credible, and it is found that the same cell may have multiple annotations, how should I understand this result?

**Comment by Jeff1995** [comment]
Yes P-value < 0.05 should be considered credible. The above screenshot should be from the query hits table, where the "cell_ontology_class" are annotations for the reference "hits" rather than prediction for query cells. The same query cell can have multiple "hits" so they appear more than once in the hits table.

To obtain prediction for query cells, you need to proceed with the prediction button (at the bottom right of the "hits" page), and perform a majority voting after P-value filtering. However, in this case, proceeding with prediction will mostly produce "rejected" cells at the default P-value cutoff = 0.05. Lifting the P-value cutoff can produce more predictions, but the results may be less reliable.

Instead, we recommend enabling the online-tuning option in "additional parameters", by setting an "Align Method", it increases query time but produces more accurate results when the batch effect between reference and query is large:

![Screen Shot 2021-03-16 at 2 56 53 PM](https://user-images.githubusercontent.com/13842130/111268142-dea46000-8667-11eb-8163-ef9aa0d3df36.jpg)
