### ISSUE TITLE
how to get h5 files ?

### ISSUE THREAD

**Issue by BinDuan** [gao-lab/Cell_BLAST#2]
The author gave examples, and the input is "data.h5", I wonder how can you get h5 file like you said with the original expression profile?

**Comment by Jeff1995** [comment]
Sorry for the delayed response. The h5 files can be found at https://cblast.gao-lab.org/download. You can click the dataset names (first column) there to download the h5 files.

**Comment by BinDuan** [comment]
Thanks for your response and it is helpful. However, what I want to know is that how should I creat "h5" files that satisfy the input of Cell_BLAST with my own data which your datasets didn't contain.

**Comment by Jeff1995** [comment]
In that case, it might be unnecessary to convert to the h5 files and load them from disk. What's the current data format you have? If it's in [AnnData](https://anndata.readthedocs.io/en/stable/) or [Loom](http://loompy.org) format, you can use the [`from_anndata`](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.from_anndata.html) or [`from_loom`](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.from_loom.html) methods to convert them into `cb.data.ExprDataSet` class, which can then be used as input of Cell BLAST. Otherwise, you may first manually read your dataset into memory, and then create a [`cb.data.ExprDataSet`](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.html) object (via the class constructor) with the expression matrix, cell meta table and gene meta table. To save the `cb.data.ExprDataSet` object to h5 files, use the [`write_dataset`](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.write_dataset.html) method.

Hope that helps!
