### ISSUE TITLE
The function of find_variable_genes is lost

### ISSUE THREAD

**Issue by Dragonlongzhilin** [gao-lab/Cell_BLAST#24]
I did not found the many function (e.g., find_variable_genes). I don't know why?
This is my code:
import Cell_BLAST as cb
![image](https://user-images.githubusercontent.com/33304280/191251996-32d764e7-57b8-46b0-96d7-6bbddb45642f.png)

**Comment by Van1yu3** [comment]
Hi, I'm not the author, but let me try to solve your problem. I think this is because you have installed version 0.3.8, but the tutorial is for the pre-release version 0.5.0. I suggest referring to the [previous commit](https://github.com/gao-lab/Cell_BLAST/tree/45b14bbd3385b8a7be0b48ef5ab42bc946f3558f) and going to the [example folder](https://github.com/gao-lab/Cell_BLAST/tree/45b14bbd3385b8a7be0b48ef5ab42bc946f3558f/Notebooks/Examples) for the tutorials adapted for version 0.3.8.

**Comment by Jeff1995** [comment]
Sorry for the inconvenience. @Van1yu3 is correct. The function is available only in the latest version v0.5.0, which was formally released just now. You may update via PyPI.
